name: flutter_chatbot_refugee
description: Chat + offline map Flutter app for refugee support
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sliding_up_panel: ^2.0.0+1
  flutter_tts: ^3.6.3
  speech_to_text: ^6.1.1
  maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: main
      path: maplibre_gl



flutter:
  uses-material-design: true

  assets:
    - assets/style.json
    - assets/sudan_tiles/

